import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import { Roboto } from 'next/font/google';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-roboto', 
  display: 'swap', 
});


export const metadata: Metadata = {
  title: "Note Hub",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
  modal,          
}: {
  children: React.ReactNode;
  modal: React.ReactNode;  
}) {
  return (
    <html lang="en">
      <body className={roboto.variable}>

        <TanStackProvider>
          <Header />
          <main>{children}</main>
          <Footer />
          {modal}          {/* ⬅️ модальные маршруты */}
        </TanStackProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}